In [83]:
import pybaseball as pb 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from pybaseball import statcast

In [84]:
dir(pb)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'all_star_full',
 'all_star_game_logs',
 'appearances',
 'awards_managers',
 'awards_players',
 'awards_share_managers',
 'awards_share_players',
 'batting',
 'batting_leaders',
 'batting_post',
 'batting_stats',
 'batting_stats_bref',
 'batting_stats_range',
 'bwar_bat',
 'bwar_pitch',
 'college_playing',
 'division_series_logs',
 'download_lahman',
 'fielding',
 'fielding_of',
 'fielding_of_split',
 'fielding_post',
 'hall_of_fame',
 'home_games',
 'lahman',
 'lcs_logs',
 'league_batting_stats',
 'league_pitching_stats',
 'managers',
 'managers_half',
 'master',
 'parks',
 'people',
 'pitching',
 'pitching_leaders',
 'pitching_post',
 'pitching_stats',
 'pitching_stats_bref',
 'pitching_stats_range',
 'playerid_lookup',
 'playerid_reverse_lookup',
 'pybaseball',
 'retrosheet',
 'salaries',
 'schedule_and_record',
 'schools',
 'season_game_logs',
 'series_post',
 'standings',
 'statcast',
 'statcast_batter',
 'statcast_pitcher',
 'statcast_single_game',
 'team_batting',
 'team_pitching',
 'team_results',
 'teams',
 'teams_franchises',
 'teams_half',
 'utils',
 'wild_card_logs',
 'world_series_logs']

In [85]:
pb.playerid_lookup("Wainwright", "Adam")

Gathering player lookup table. This may take a moment.

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,wainwright,adam,425794,waina001,wainwad01,2233,2005.0,2019.0

In [86]:
pb.statcast_pitcher("2005-01-01","2019-01-01",425794)

Gathering Player Data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,CH,2010-09-24,81.0,NaN,NaN,Adam Wainwright,430957.0,425794,field_out,hit_into_play,...,1,7,1,7,7,1,1,7,NaN,NaN
1,CU,2010-09-24,69.2,NaN,NaN,Adam Wainwright,455088.0,425794,field_out,hit_into_play,...,1,7,1,7,7,1,1,7,NaN,NaN
2,CH,2010-09-24,87.1,NaN,NaN,Adam Wainwright,294558.0,425794,single,hit_into_play_no_out,...,1,7,1,7,7,1,1,7,NaN,NaN
3,CU,2010-09-24,71.0,NaN,NaN,Adam Wainwright,294558.0,425794,NaN,swinging_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
4,SI,2010-09-24,90.2,NaN,NaN,Adam Wainwright,133380.0,425794,double,hit_into_play_no_out,...,1,7,1,7,7,1,1,7,NaN,NaN
5,CU,2010-09-24,70.8,NaN,NaN,Adam Wainwright,133380.0,425794,NaN,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
6,CH,2010-09-24,80.0,NaN,NaN,Adam Wainwright,133380.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
7,CH,2010-09-24,86.8,NaN,NaN,Adam Wainwright,133380.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
8,CU,2010-09-24,68.2,NaN,NaN,Adam Wainwright,133380.0,425794,NaN,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
9,SI,2010-09-24,88.2,NaN,NaN,Adam Wainwright,493120.0,425794,field_out,hit_into_play,...,1,7,1,7,7,1,1,7,NaN,NaN
10,CH,2010-09-24,78.8,NaN,NaN,Adam Wainwright,493120.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
11,SI,2010-09-24,88.4,NaN,NaN,Adam Wainwright,493120.0,425794,NaN,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
12,CH,2010-09-24,86.5,NaN,NaN,Adam Wainwright,493120.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
13,CU,2010-09-24,67.5,NaN,NaN,Adam Wainwright,493120.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
14,SI,2010-09-24,89.3,NaN,NaN,Adam Wainwright,516770.0,425794,field_out,hit_into_play,...,1,7,1,7,7,1,1,7,NaN,NaN
15,CU,2010-09-24,70.0,NaN,NaN,Adam Wainwright,516770.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
16,CU,2010-09-24,70.1,NaN,NaN,Adam Wainwright,516770.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
17,SI,2010-09-24,88.8,NaN,NaN,Adam Wainwright,516770.0,425794,NaN,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
18,FC,2010-09-24,83.9,NaN,NaN,Adam Wainwright,453539.0,425794,strikeout,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
19,CU,2010-09-24,73.1,NaN,NaN,Adam Wainwright,453539.0,425794,NaN,foul,...,1,7,1,7,7,1,1,7,NaN,NaN
20,CH,2010-09-24,81.9,NaN,NaN,Adam Wainwright,453539.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
21,SI,2010-09-24,90.9,NaN,NaN,Adam Wainwright,453539.0,425794,NaN,foul,...,1,7,1,7,7,1,1,7,NaN,NaN
22,SI,2010-09-24,87.5,NaN,NaN,Adam Wainwright,453539.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
23,CH,2010-09-24,78.9,NaN,NaN,Adam Wainwright,453539.0,425794,NaN,foul,...,1,7,1,7,7,1,1,7,NaN,NaN
24,SI,2010-09-24,87.2,NaN,NaN,Adam Wainwright,453539.0,425794,NaN,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
25,CU,2010-09-24,70.2,NaN,NaN,Adam Wainwright,446381.0,425794,field_out,hit_into_play,...,1,7,1,7,7,1,1,7,NaN,NaN
26,CU,2010-09-24,70.2,NaN,NaN,Adam Wainwright,446381.0,425794,NaN,swinging_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
27,CH,2010-09-24,86.4,NaN,NaN,Adam Wainwright,446381.0,425794,NaN,ball,...,1,7,1,7,7,1,1,7,NaN,NaN
28,CU,2010-09-24,68.5,NaN,NaN,Adam Wainwright,446381.0,425794,NaN,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
29,CU,2010-09-24,73.7,NaN,NaN,Adam Wainwright,425542.0,425794,strikeout,called_strike,...,1,7,1,7,7,1,1,7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,FC,2017-04-04,88.2,-0.9109,6.3120,Adam Wainwright,518792.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2858,CU,2017-04-04,77.7,-0.8230,6.3028,Adam Wainwright,518792.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2859,NaN,2017-04-04,NaN,NaN,NaN,Adam Wainwright,518792.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,NaN,NaN
2860,NaN,2017-04-04,NaN,NaN,NaN,Adam Wainwright,518792.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,NaN,NaN
2861,NaN,2017-04-04,NaN,NaN,NaN,Adam Wainwright,575929.0,425794,strikeout,called_strike,...,0,0,0,0,0,0,0,0,NaN,NaN
2862,SI,2017-04-04,91.9,-1.2133,6.2429,Adam Wainwright,575929.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2863,CU,2017-04-04,73.9,-1.0014,6.2954,Adam Wainwright,575929.0,425794,NaN,swinging_strike,...,0,0,0,0,0,0,0,0,Standard,Standard
2864,SI,2017-04-04,90.7,-1.2937,6.1580,Adam Wainwright,575929.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2865,SI,2017-04-04,89.8,-1.1693,6.1857,Adam Wainwright,575929.0,425794,NaN,foul_bunt,...,0,0,0,0,0,0,0,0,Standard,Standard
2866,FC,2017-04-04,87.6,-1.0768,6.1291,Adam Wainwright,608365.0,425794,field_out,hit_into_play,...,0,0,0,0,0,0,0,0,Standard,Standard
2867,CU,2017-04-04,77.8,-0.9545,6.3471,Adam Wainwright,608365.0,425794,NaN,blocked_ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2868,SI,2017-04-04,92.7,-1.1875,6.1275,Adam Wainwright,608365.0,425794,NaN,swinging_strike,...,0,0,0,0,0,0,0,0,Standard,Standard
2869,FC,2017-04-04,86.4,-1.1060,6.2886,Adam Wainwright,608365.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,Standard,Standard
2870,CU,2017-04-04,75.9,-1.0769,6.3853,Adam Wainwright,608365.0,425794,NaN,blocked_ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2871,FF,2017-04-04,91.7,-1.1393,6.1796,Adam Wainwright,608365.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2872,FC,2017-04-04,87.7,-1.1446,6.2554,Adam Wainwright,519203.0,425794,field_out,hit_into_play,...,0,0,0,0,0,0,0,0,Standard,Standard
2873,CU,2017-04-04,75.5,-1.1132,6.3660,Adam Wainwright,519203.0,425794,NaN,called_strike,...,0,0,0,0,0,0,0,0,Strategic,Standard
2874,CH,2017-04-04,85.5,-1.2754,6.2656,Adam Wainwright,519203.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2875,FF,2017-04-04,92.3,-1.0819,6.2643,Adam Wainwright,519203.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,Standard,Standard
2876,CU,2017-04-04,76.5,-1.1012,6.2565,Adam Wainwright,592178.0,425794,field_out,hit_into_play,...,0,0,0,0,0,0,0,0,Standard,Standard
2877,CU,2017-04-04,78.4,-1.1592,6.1843,Adam Wainwright,592178.0,425794,NaN,blocked_ball,...,0,0,0,0,0,0,0,0,Standard,Standard
2878,SI,2017-04-04,93.0,-1.3202,5.9450,Adam Wainwright,592178.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,Standard,Standard
2879,FF,2017-04-04,93.1,-1.0855,6.1899,Adam Wainwright,656941.0,425794,walk,ball,...,0,0,0,0,0,0,0,0,Strategic,Standard
2880,FC,2017-04-04,89.8,-1.0337,6.1102,Adam Wainwright,656941.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,Strategic,Standard
2881,FC,2017-04-04,84.9,-1.2949,6.0576,Adam Wainwright,656941.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Strategic,Standard
2882,CU,2017-04-04,76.5,-0.8438,6.2958,Adam Wainwright,656941.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Strategic,Standard
2883,CU,2017-04-04,75.8,-0.9654,6.2720,Adam Wainwright,656941.0,425794,NaN,foul,...,0,0,0,0,0,0,0,0,Standard,Standard
2884,FF,2017-04-04,92.1,-0.9347,6.1646,Adam Wainwright,656941.0,425794,NaN,foul_tip,...,0,0,0,0,0,0,0,0,Standard,Standard
2885,FC,2017-04-04,87.9,-1.2925,6.0722,Adam Wainwright,656941.0,425794,NaN,swinging_strike,...,0,0,0,0,0,0,0,0,Standard,Standard
2886,SI,2017-04-04,91.3,-1.1948,6.1291,Adam Wainwright,656941.0,425794,NaN,ball,...,0,0,0,0,0,0,0,0,Standard,Standard

In [87]:
seasons = {'2010':{'start_date': '2010-04-04', 'end_date': '2010-11-01'},
           '2011':{'start_date': '2011-03-31', 'end_date': '2011-10-28'},
           '2012':{'start_date': '2012-03-28', 'end_date': '2012-10-28'},
           '2013':{'start_date': '2013-03-31', 'end_date': '2013-10-30'},
           '2014':{'start_date': '2014-03-22', 'end_date': '2014-10-29'},
           '2015':{'start_date': '2015-04-05', 'end_date': '2015-11-01'},
           '2016':{'start_date': '2016-04-03', 'end_date': '2016-11-02'},
           '2017':{'start_date': '2017-04-02', 'end_date': '2017-11-01'},
           '2018':{'start_date': '2018-03-29', 'end_date': '2018-10-28'},
           '2019':{'start_date': '2019-03-20', 'end_date': '2019-10-30'}
           }


def pull_clean_and_pickle(start_date, end_date, year):

    # Pull in DataFrame from statcast
    df = statcast(start_dt = start_date, end_dt = end_date)

    # Drop depriciated and extraneous features
    df = df.drop(columns = ['spin_dir','spin_rate_deprecated',
         'break_angle_deprecated','break_length_deprecated', 'game_type',
         'tfs_deprecated', 'tfs_zulu_deprecated', 'umpire'])

    # Sort pitches chronologically
    df = df.sort_values(by = ['game_date', 'game_pk', 'at_bat_number', 'pitch_number'])

#     # Pickle DataFrame
#     df.to_pickle(path=(
#     "/Users/mattkirby/repos/RC-v1.0--Data-Gathering/season_pickles/pitches_" + year + ".pkl"
#     ),compression='zip')


for year in seasons.keys():
  start_date = seasons[year]['start_date']
  end_date = seasons[year]['end_date']
  pull_clean_and_pickle(start_date, end_date, year)

This is a large query, it may take a moment to complete
Completed sub-query from 2010-04-04 to 2010-04-09
Completed sub-query from 2010-04-10 to 2010-04-15
Completed sub-query from 2010-04-16 to 2010-04-21
Completed sub-query from 2010-04-22 to 2010-04-27
Completed sub-query from 2010-04-28 to 2010-05-03
Completed sub-query from 2010-05-04 to 2010-05-09
Completed sub-query from 2010-05-10 to 2010-05-15
Completed sub-query from 2010-05-16 to 2010-05-21
Completed sub-query from 2010-05-22 to 2010-05-27
Completed sub-query from 2010-05-28 to 2010-06-02
Completed sub-query from 2010-06-03 to 2010-06-08
Completed sub-query from 2010-06-09 to 2010-06-14
Completed sub-query from 2010-06-15 to 2010-06-20
Completed sub-query from 2010-06-21 to 2010-06-26
Completed sub-query from 2010-06-27 to 2010-07-02
Completed sub-query from 2010-07-03 to 2010-07-08
Completed sub-query from 2010-07-09 to 2010-07-14
Completed sub-query from 2010-07-15 to 2010-07-20
Completed sub-query from 2010-07-21 to 2010-07-26
Completed sub-query from 2010-07-27 to 2010-08-01
Completed sub-query from 2010-08-02 to 2010-08-07
Completed sub-query from 2010-08-08 to 2010-08-13
Completed sub-query from 2010-08-14 to 2010-08-19
Completed sub-query from 2010-08-20 to 2010-08-25
Completed sub-query from 2010-08-26 to 2010-08-31
Completed sub-query from 2010-09-01 to 2010-09-06
Completed sub-query from 2010-09-07 to 2010-09-12
Completed sub-query from 2010-09-13 to 2010-09-18
Completed sub-query from 2010-09-19 to 2010-09-24
Completed sub-query from 2010-09-25 to 2010-09-30
Completed sub-query from 2010-10-01 to 2010-10-06
Completed sub-query from 2010-10-07 to 2010-10-12
Completed sub-query from 2010-10-13 to 2010-10-18
Completed sub-query from 2010-10-19 to 2010-10-24
Completed sub-query from 2010-10-25 to 2010-10-30
Completed sub-query from 2010-10-31 to 2010-11-01
This is a large query, it may take a moment to complete
Completed sub-query from 2011-03-31 to 2011-04-05
Completed sub-query from 2011-04-06 to 2011-04-11
Completed sub-query from 2011-04-12 to 2011-04-17
Completed sub-query from 2011-04-18 to 2011-04-23
Completed sub-query from 2011-04-24 to 2011-04-29
Completed sub-query from 2011-04-30 to 2011-05-05
Completed sub-query from 2011-05-06 to 2011-05-11
Completed sub-query from 2011-05-12 to 2011-05-17
Completed sub-query from 2011-05-18 to 2011-05-23
Completed sub-query from 2011-05-24 to 2011-05-29
Completed sub-query from 2011-05-30 to 2011-06-04
Completed sub-query from 2011-06-05 to 2011-06-10
Completed sub-query from 2011-06-11 to 2011-06-16
Completed sub-query from 2011-06-17 to 2011-06-22
Completed sub-query from 2011-06-23 to 2011-06-28
Completed sub-query from 2011-06-29 to 2011-07-04
Completed sub-query from 2011-07-05 to 2011-07-10
Completed sub-query from 2011-07-11 to 2011-07-16
Completed sub-query from 2011-07-17 to 2011-07-22
Completed sub-query from 2011-07-23 to 2011-07-28
Completed sub-query from 2011-07-29 to 2011-08-03
Completed sub-query from 2011-08-04 to 2011-08-09
Completed sub-query from 2011-08-10 to 2011-08-15
Completed sub-query from 2011-08-16 to 2011-08-21
Completed sub-query from 2011-08-22 to 2011-08-27
Completed sub-query from 2011-08-28 to 2011-09-02
Completed sub-query from 2011-09-03 to 2011-09-08
Completed sub-query from 2011-09-09 to 2011-09-14
Completed sub-query from 2011-09-15 to 2011-09-20
Completed sub-query from 2011-09-21 to 2011-09-26
Completed sub-query from 2011-09-27 to 2011-10-02
Completed sub-query from 2011-10-03 to 2011-10-08
Completed sub-query from 2011-10-09 to 2011-10-14
Completed sub-query from 2011-10-15 to 2011-10-20
Completed sub-query from 2011-10-21 to 2011-10-26
Completed sub-query from 2011-10-27 to 2011-10-28
This is a large query, it may take a moment to complete
Completed sub-query from 2012-03-28 to 2012-04-02
Completed sub-query from 2012-04-03 to 2012-04-08
Completed sub-query from 2012-04-09 to 2012-04-14
Completed sub-query from 2012-04-15 to 2012-04-20
Completed sub-query from 2012-04-21 to 2012-04-26
Completed sub-query from 2012-04-27 to 2012-05-02
Completed sub-query from 2012-05-03 to 2012-05-08
Completed sub-query from 2012-05-09 to 2012-05-14
Completed sub-query from 2012-05-15 to 2012-05-20
Completed sub-query from 2012-05-21 to 2012-05-26
Completed sub-query from 2012-05-27 to 2012-06-01
Completed sub-query from 2012-06-02 to 2012-06-07
Completed sub-query from 2012-06-08 to 2012-06-13
Completed sub-query from 2012-06-14 to 2012-06-19
Completed sub-query from 2012-06-20 to 2012-06-25
Completed sub-query from 2012-06-26 to 2012-07-01
Completed sub-query from 2012-07-02 to 2012-07-07
Completed sub-query from 2012-07-08 to 2012-07-13
Completed sub-query from 2012-07-14 to 2012-07-19
Completed sub-query from 2012-07-20 to 2012-07-25
Completed sub-query from 2012-07-26 to 2012-07-31
Completed sub-query from 2012-08-01 to 2012-08-06
Completed sub-query from 2012-08-07 to 2012-08-12
Completed sub-query from 2012-08-13 to 2012-08-18
Completed sub-query from 2012-08-19 to 2012-08-24
Completed sub-query from 2012-08-25 to 2012-08-30
Completed sub-query from 2012-08-31 to 2012-09-05
Completed sub-query from 2012-09-06 to 2012-09-11
Completed sub-query from 2012-09-12 to 2012-09-17
Completed sub-query from 2012-09-18 to 2012-09-23
Completed sub-query from 2012-09-24 to 2012-09-29
Completed sub-query from 2012-09-30 to 2012-10-05
Completed sub-query from 2012-10-06 to 2012-10-11
Completed sub-query from 2012-10-12 to 2012-10-17
Completed sub-query from 2012-10-18 to 2012-10-23
Completed sub-query from 2012-10-24 to 2012-10-28
This is a large query, it may take a moment to complete
Completed sub-query from 2013-03-31 to 2013-04-05
Completed sub-query from 2013-04-06 to 2013-04-11
Completed sub-query from 2013-04-12 to 2013-04-17
Completed sub-query from 2013-04-18 to 2013-04-23

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DtypeWarning: Columns (8,15,23) have mixed types. Specify dtype option on import or set low_memory=False.

Completed sub-query from 2013-04-24 to 2013-04-29
Completed sub-query from 2013-04-30 to 2013-05-05
Completed sub-query from 2013-05-06 to 2013-05-11
Completed sub-query from 2013-05-12 to 2013-05-17
Completed sub-query from 2013-05-18 to 2013-05-23
Completed sub-query from 2013-05-24 to 2013-05-29
Completed sub-query from 2013-05-30 to 2013-06-04
Completed sub-query from 2013-06-05 to 2013-06-10
Completed sub-query from 2013-06-11 to 2013-06-16
Completed sub-query from 2013-06-17 to 2013-06-22
Completed sub-query from 2013-06-23 to 2013-06-28
Completed sub-query from 2013-06-29 to 2013-07-04
Completed sub-query from 2013-07-05 to 2013-07-10
Completed sub-query from 2013-07-11 to 2013-07-16
Completed sub-query from 2013-07-17 to 2013-07-22
Completed sub-query from 2013-07-23 to 2013-07-28
Completed sub-query from 2013-07-29 to 2013-08-03
Completed sub-query from 2013-08-04 to 2013-08-09
Completed sub-query from 2013-08-10 to 2013-08-15
Completed sub-query from 2013-08-16 to 2013-08-21
Completed sub-query from 2013-08-22 to 2013-08-27
Completed sub-query from 2013-08-28 to 2013-09-02
Completed sub-query from 2013-09-03 to 2013-09-08
Completed sub-query from 2013-09-09 to 2013-09-14
Completed sub-query from 2013-09-15 to 2013-09-20
Completed sub-query from 2013-09-21 to 2013-09-26
Completed sub-query from 2013-09-27 to 2013-10-02
Completed sub-query from 2013-10-03 to 2013-10-08
Completed sub-query from 2013-10-09 to 2013-10-14
Completed sub-query from 2013-10-15 to 2013-10-20
Completed sub-query from 2013-10-21 to 2013-10-26
Completed sub-query from 2013-10-27 to 2013-10-30
This is a large query, it may take a moment to complete
Completed sub-query from 2014-03-22 to 2014-03-27
Completed sub-query from 2014-03-28 to 2014-04-02
Completed sub-query from 2014-04-03 to 2014-04-08
Completed sub-query from 2014-04-09 to 2014-04-14
Completed sub-query from 2014-04-15 to 2014-04-20
Completed sub-query from 2014-04-21 to 2014-04-26
Completed sub-query from 2014-04-27 to 2014-05-02
Completed sub-query from 2014-05-03 to 2014-05-08
Completed sub-query from 2014-05-09 to 2014-05-14
Completed sub-query from 2014-05-15 to 2014-05-20
Completed sub-query from 2014-05-21 to 2014-05-26
Completed sub-query from 2014-05-27 to 2014-06-01
Completed sub-query from 2014-06-02 to 2014-06-07
Completed sub-query from 2014-06-08 to 2014-06-13
Completed sub-query from 2014-06-14 to 2014-06-19
Completed sub-query from 2014-06-20 to 2014-06-25
Completed sub-query from 2014-06-26 to 2014-07-01
Completed sub-query from 2014-07-02 to 2014-07-07
Completed sub-query from 2014-07-08 to 2014-07-13
Completed sub-query from 2014-07-14 to 2014-07-19
Completed sub-query from 2014-07-20 to 2014-07-25
Completed sub-query from 2014-07-26 to 2014-07-31
Completed sub-query from 2014-08-01 to 2014-08-06
Completed sub-query from 2014-08-07 to 2014-08-12
Completed sub-query from 2014-08-13 to 2014-08-18
Completed sub-query from 2014-08-19 to 2014-08-24
Completed sub-query from 2014-08-25 to 2014-08-30
Completed sub-query from 2014-08-31 to 2014-09-05
Completed sub-query from 2014-09-06 to 2014-09-11
Completed sub-query from 2014-09-12 to 2014-09-17
Completed sub-query from 2014-09-18 to 2014-09-23
Completed sub-query from 2014-09-24 to 2014-09-29
Completed sub-query from 2014-09-30 to 2014-10-05
Completed sub-query from 2014-10-06 to 2014-10-11
Completed sub-query from 2014-10-12 to 2014-10-17
Completed sub-query from 2014-10-18 to 2014-10-23
Completed sub-query from 2014-10-24 to 2014-10-29
This is a large query, it may take a moment to complete
Completed sub-query from 2015-04-05 to 2015-04-10
Completed sub-query from 2015-04-11 to 2015-04-16
Completed sub-query from 2015-04-17 to 2015-04-22
Completed sub-query from 2015-04-23 to 2015-04-28
Completed sub-query from 2015-04-29 to 2015-05-04
Completed sub-query from 2015-05-05 to 2015-05-10
Completed sub-query from 2015-05-11 to 2015-05-16
Completed sub-query from 2015-05-17 to 2015-05-22
Completed sub-query from 2015-05-23 to 2015-05-28
Completed sub-query from 2015-05-29 to 2015-06-03
Completed sub-query from 2015-06-04 to 2015-06-09
Completed sub-query from 2015-06-10 to 2015-06-15
Completed sub-query from 2015-06-16 to 2015-06-21
Completed sub-query from 2015-06-22 to 2015-06-27
Completed sub-query from 2015-06-28 to 2015-07-03
Completed sub-query from 2015-07-04 to 2015-07-09
Completed sub-query from 2015-07-10 to 2015-07-15
Completed sub-query from 2015-07-16 to 2015-07-21
Completed sub-query from 2015-07-22 to 2015-07-27
Completed sub-query from 2015-07-28 to 2015-08-02
Completed sub-query from 2015-08-03 to 2015-08-08
Completed sub-query from 2015-08-09 to 2015-08-14
Completed sub-query from 2015-08-15 to 2015-08-20
Completed sub-query from 2015-08-21 to 2015-08-26
Completed sub-query from 2015-08-27 to 2015-09-01
Completed sub-query from 2015-09-02 to 2015-09-07
Completed sub-query from 2015-09-08 to 2015-09-13
Completed sub-query from 2015-09-14 to 2015-09-19
Completed sub-query from 2015-09-20 to 2015-09-25
Completed sub-query from 2015-09-26 to 2015-10-01
Completed sub-query from 2015-10-02 to 2015-10-07
Completed sub-query from 2015-10-08 to 2015-10-13
Completed sub-query from 2015-10-14 to 2015-10-19
Completed sub-query from 2015-10-20 to 2015-10-25
Completed sub-query from 2015-10-26 to 2015-10-31
Completed sub-query from 2015-11-01 to 2015-11-01
This is a large query, it may take a moment to complete
Completed sub-query from 2016-04-03 to 2016-04-08
Completed sub-query from 2016-04-09 to 2016-04-14
Completed sub-query from 2016-04-15 to 2016-04-20
Completed sub-query from 2016-04-21 to 2016-04-26
Completed sub-query from 2016-04-27 to 2016-05-02
Completed sub-query from 2016-05-03 to 2016-05-08
Completed sub-query from 2016-05-09 to 2016-05-14
Completed sub-query from 2016-05-15 to 2016-05-20
Completed sub-query from 2016-05-21 to 2016-05-26
Completed sub-query from 2016-05-27 to 2016-06-01
Completed sub-query from 2016-06-02 to 2016-06-07
Completed sub-query from 2016-06-08 to 2016-06-13
Completed sub-query from 2016-06-14 to 2016-06-19
Completed sub-query from 2016-06-20 to 2016-06-25
Completed sub-query from 2016-06-26 to 2016-07-01
Completed sub-query from 2016-07-02 to 2016-07-07
Completed sub-query from 2016-07-08 to 2016-07-13
Completed sub-query from 2016-07-14 to 2016-07-19
Completed sub-query from 2016-07-20 to 2016-07-25
Completed sub-query from 2016-07-26 to 2016-07-31
Completed sub-query from 2016-08-01 to 2016-08-06
Completed sub-query from 2016-08-07 to 2016-08-12
Completed sub-query from 2016-08-13 to 2016-08-18
Completed sub-query from 2016-08-19 to 2016-08-24
Completed sub-query from 2016-08-25 to 2016-08-30
Completed sub-query from 2016-08-31 to 2016-09-05
Completed sub-query from 2016-09-06 to 2016-09-11
Completed sub-query from 2016-09-12 to 2016-09-17
Completed sub-query from 2016-09-18 to 2016-09-23
Completed sub-query from 2016-09-24 to 2016-09-29
Completed sub-query from 2016-09-30 to 2016-10-05
Completed sub-query from 2016-10-06 to 2016-10-11
Completed sub-query from 2016-10-12 to 2016-10-17
Completed sub-query from 2016-10-18 to 2016-10-23
Completed sub-query from 2016-10-24 to 2016-10-29
Completed sub-query from 2016-10-30 to 2016-11-02
This is a large query, it may take a moment to complete
Completed sub-query from 2017-04-02 to 2017-04-07
Completed sub-query from 2017-04-08 to 2017-04-13
Completed sub-query from 2017-04-14 to 2017-04-19
Completed sub-query from 2017-04-20 to 2017-04-25
Completed sub-query from 2017-04-26 to 2017-05-01
Completed sub-query from 2017-05-02 to 2017-05-07
Completed sub-query from 2017-05-08 to 2017-05-13
Completed sub-query from 2017-05-14 to 2017-05-19
Completed sub-query from 2017-05-20 to 2017-05-25
Completed sub-query from 2017-05-26 to 2017-05-31
Completed sub-query from 2017-06-01 to 2017-06-06
Completed sub-query from 2017-06-07 to 2017-06-12
Completed sub-query from 2017-06-13 to 2017-06-18
Completed sub-query from 2017-06-19 to 2017-06-24
Completed sub-query from 2017-06-25 to 2017-06-30
Completed sub-query from 2017-07-01 to 2017-07-06
Completed sub-query from 2017-07-07 to 2017-07-12
Completed sub-query from 2017-07-13 to 2017-07-18
Completed sub-query from 2017-07-19 to 2017-07-24

Completed sub-query from 2017-07-25 to 2017-07-30
Completed sub-query from 2017-07-31 to 2017-08-05
Completed sub-query from 2017-08-06 to 2017-08-11
Completed sub-query from 2017-08-12 to 2017-08-17
Completed sub-query from 2017-08-18 to 2017-08-23
Completed sub-query from 2017-08-24 to 2017-08-29
Completed sub-query from 2017-08-30 to 2017-09-04
Completed sub-query from 2017-09-05 to 2017-09-10
Completed sub-query from 2017-09-11 to 2017-09-16
Completed sub-query from 2017-09-17 to 2017-09-22
Completed sub-query from 2017-09-23 to 2017-09-28
Completed sub-query from 2017-09-29 to 2017-10-04
Completed sub-query from 2017-10-05 to 2017-10-10
Completed sub-query from 2017-10-11 to 2017-10-16
Completed sub-query from 2017-10-17 to 2017-10-22
Completed sub-query from 2017-10-23 to 2017-10-28
Completed sub-query from 2017-10-29 to 2017-11-01
This is a large query, it may take a moment to complete
Completed sub-query from 2018-03-29 to 2018-04-03
Completed sub-query from 2018-04-04 to 2018-04-09
Completed sub-query from 2018-04-10 to 2018-04-15
Completed sub-query from 2018-04-16 to 2018-04-21
Completed sub-query from 2018-04-22 to 2018-04-27
Completed sub-query from 2018-04-28 to 2018-05-03
Completed sub-query from 2018-05-04 to 2018-05-09
Completed sub-query from 2018-05-10 to 2018-05-15
Completed sub-query from 2018-05-16 to 2018-05-21
Completed sub-query from 2018-05-22 to 2018-05-27
Completed sub-query from 2018-05-28 to 2018-06-02
Completed sub-query from 2018-06-03 to 2018-06-08
Completed sub-query from 2018-06-09 to 2018-06-14
Completed sub-query from 2018-06-15 to 2018-06-20
Completed sub-query from 2018-06-21 to 2018-06-26
Completed sub-query from 2018-06-27 to 2018-07-02
Completed sub-query from 2018-07-03 to 2018-07-08
Completed sub-query from 2018-07-09 to 2018-07-14
Completed sub-query from 2018-07-15 to 2018-07-20
Completed sub-query from 2018-07-21 to 2018-07-26
Completed sub-query from 2018-07-27 to 2018-08-01
Completed sub-query from 2018-08-02 to 2018-08-07
Completed sub-query from 2018-08-08 to 2018-08-13
Completed sub-query from 2018-08-14 to 2018-08-19
Completed sub-query from 2018-08-20 to 2018-08-25
Completed sub-query from 2018-08-26 to 2018-08-31
Completed sub-query from 2018-09-01 to 2018-09-06
Completed sub-query from 2018-09-07 to 2018-09-12
Completed sub-query from 2018-09-13 to 2018-09-18
Completed sub-query from 2018-09-19 to 2018-09-24
Completed sub-query from 2018-09-25 to 2018-09-30
Completed sub-query from 2018-10-01 to 2018-10-06
Completed sub-query from 2018-10-07 to 2018-10-12
Completed sub-query from 2018-10-13 to 2018-10-18
Completed sub-query from 2018-10-19 to 2018-10-24
Completed sub-query from 2018-10-25 to 2018-10-28
This is a large query, it may take a moment to complete
Completed sub-query from 2019-03-20 to 2019-03-25
Completed sub-query from 2019-03-26 to 2019-03-31
Completed sub-query from 2019-04-01 to 2019-04-06
Completed sub-query from 2019-04-07 to 2019-04-12
Completed sub-query from 2019-04-13 to 2019-04-18
Completed sub-query from 2019-04-19 to 2019-04-24
Completed sub-query from 2019-04-25 to 2019-04-30
Completed sub-query from 2019-05-01 to 2019-05-06
Completed sub-query from 2019-05-07 to 2019-05-12
Completed sub-query from 2019-05-13 to 2019-05-18
Completed sub-query from 2019-05-19 to 2019-05-24
Completed sub-query from 2019-05-25 to 2019-05-30
Completed sub-query from 2019-05-31 to 2019-06-05
Completed sub-query from 2019-06-06 to 2019-06-11
Completed sub-query from 2019-06-12 to 2019-06-17
Completed sub-query from 2019-06-18 to 2019-06-23
Completed sub-query from 2019-06-24 to 2019-06-29
Completed sub-query from 2019-06-30 to 2019-07-05
Completed sub-query from 2019-07-06 to 2019-07-11
Completed sub-query from 2019-07-12 to 2019-07-17
Completed sub-query from 2019-07-18 to 2019-07-23
Completed sub-query from 2019-07-24 to 2019-07-29
Completed sub-query from 2019-07-30 to 2019-08-04
Completed sub-query from 2019-08-05 to 2019-08-10
Completed sub-query from 2019-08-11 to 2019-08-16
Completed sub-query from 2019-08-17 to 2019-08-22
Completed sub-query from 2019-08-23 to 2019-08-28
Completed sub-query from 2019-08-29 to 2019-09-03
Completed sub-query from 2019-09-04 to 2019-09-09
Completed sub-query from 2019-09-10 to 2019-09-15
Completed sub-query from 2019-09-16 to 2019-09-21
Completed sub-query from 2019-09-22 to 2019-09-27
Completed sub-query from 2019-09-28 to 2019-10-03
Query unsuccessful for data from 2019-10-04 to 2019-10-08. Skipping these dates.
Query unsuccessful for data from 2019-10-09 to 2019-10-09. Skipping these dates.
Query unsuccessful for data from 2019-10-10 to 2019-10-14. Skipping these dates.
Query unsuccessful for data from 2019-10-15 to 2019-10-15. Skipping these dates.
Query unsuccessful for data from 2019-10-16 to 2019-10-20. Skipping these dates.
Query unsuccessful for data from 2019-10-21 to 2019-10-21. Skipping these dates.
Query unsuccessful for data from 2019-10-22 to 2019-10-26. Skipping these dates.
Query unsuccessful for data from 2019-10-27 to 2019-10-27. Skipping these dates.
Completed sub-query from 2019-10-28 to 2019-10-30

In [110]:
def framer(start_dt,end_dt,year):
    '''pull from statcast and save to df'''
     # Pull in DataFrame from statcast
    df = statcast(start_dt, end_dt)

    # Drop depriciated and extraneous features
    df= df.drop(columns = ['spin_dir','spin_rate_deprecated',
         'break_angle_deprecated','break_length_deprecated', 'game_type',
         'tfs_deprecated', 'tfs_zulu_deprecated', 'umpire'])
    return df

In [131]:
dfp =framer("2010-03-01","2010-04-15",2010)
dfp.info

This is a large query, it may take a moment to complete
Completed sub-query from 2010-03-01 to 2010-04-15

<bound method DataFrame.info of        index pitch_type  game_date  release_speed  release_pos_x  \
0        361         SL 2010-04-15           83.2            NaN
1        367         SL 2010-04-15           84.3            NaN
2        379         CH 2010-04-15           85.2            NaN
3        381         SL 2010-04-15           85.4            NaN
4        393         SL 2010-04-15           83.4            NaN
5        397         SL 2010-04-15           85.1            NaN
6        411         FF 2010-04-15           92.1            NaN
7        417         FF 2010-04-15           92.5            NaN
8        426         CH 2010-04-15           86.6            NaN
9        429         SL 2010-04-15           84.3            NaN
10       443         FF 2010-04-15           93.0            NaN
11       447         FF 2010-04-15           92.4            NaN
12       460         FF 2010-04-15           92.1            NaN
13       466         FF 2010-04-15           94.5            NaN
14       480         FC 2010-04-15           88.2            NaN
15       482         FF 2010-04-15           91.4            NaN
16       501         FO 2010-04-15           82.9            NaN
17       503         FO 2010-04-15           82.5            NaN
18       518         FF 2010-04-15           92.8            NaN
19       526         SI 2010-04-15           93.6            NaN
20       539         FO 2010-04-15           82.4            NaN
21       555         SL 2010-04-15           79.7            NaN
22       558         SL 2010-04-15           81.6            NaN
23       578         SI 2010-04-15           94.3            NaN
24       580         FF 2010-04-15           94.2            NaN
25       599         SL 2010-04-15           82.8            NaN
26       602         FF 2010-04-15           93.4            NaN
27       619         SI 2010-04-15           92.6            NaN
28       628         FC 2010-04-15           89.7            NaN
29       644         FF 2010-04-15           92.7            NaN
...      ...        ...        ...            ...            ...
39970  39603         FT 2010-04-05           89.7            NaN
39971  39620         SL 2010-04-05           83.4            NaN
39972  39631         CH 2010-04-05           80.2            NaN
39973  39648         FF 2010-04-05           90.7            NaN
39974  39655         SL 2010-04-05           83.0            NaN
39975  39672         FF 2010-04-05           90.2            NaN
39976  39685         CH 2010-04-05           83.1            NaN
39977  39702         FT 2010-04-05           89.7            NaN
39978  39718         FT 2010-04-05           88.7            NaN
39979  39721         SL 2010-04-05           80.7            NaN
39980  39740         SL 2010-04-05           80.9            NaN
39981  39756         SL 2010-04-05           79.5            NaN
39982  39771         SL 2010-04-05           79.3            NaN
39983  39783         SL 2010-04-05           80.2            NaN
39984  39791         SI 2010-04-05           87.9            NaN
39985  39810         SL 2010-04-05           80.8            NaN
39986  39820         SI 2010-04-05           89.1            NaN
39987  39834         SI 2010-04-05           89.2            NaN
39988  39848         SI 2010-04-05           90.1            NaN
39989  39860         SL 2010-04-05           82.4            NaN
39990  39875         FF 2010-04-05           90.3            NaN
39991  39877         FF 2010-04-05           91.3            NaN
39992  39895         SL 2010-04-05           83.5            NaN
39993  39914         FF 2010-04-05           91.3            NaN
39994  39916         FF 2010-04-05           91.0            NaN
39995  39935         SL 2010-04-05           82.6            NaN
39996  39941         FT 2010-04-05           91.2            NaN
39997  39964         FT 2010-04-05           88.8            NaN
39998  39979         SL 2010-04-05           82.6            NaN
39999  39981         FF 2010-04-05           90.0            NaN

       release_pos_z      player_name    batter   pitcher       events  ...  \
0                NaN     Jason Frasor  493351.0  430630.0    field_out  ...
1                NaN     Jason Frasor  493351.0  430630.0          NaN  ...
2                NaN     Jason Frasor  493351.0  430630.0          NaN  ...
3                NaN     Jason Frasor  493351.0  430630.0          NaN  ...
4                NaN     Jason Frasor  493351.0  430630.0          NaN  ...
5                NaN     Jason Frasor  425567.0  430630.0    field_out  ...
6                NaN     Jason Frasor  425567.0  430630.0          NaN  ...
7                NaN     Jason Frasor  116662.0  430630.0    strikeout  ...
8                NaN     Jason Frasor  116662.0  430630.0          NaN  ...
9                NaN     Jason Frasor  116662.0  430630.0          NaN  ...
10               NaN     Jason Frasor  116662.0  430630.0          NaN  ...
11               NaN     Jason Frasor  116662.0  430630.0          NaN  ...
12               NaN     Jason Frasor  116662.0  430630.0          NaN  ...
13               NaN  Scott Linebrink  407489.0  276530.0    strikeout  ...
14               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
15               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
16               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
17               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
18               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
19               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
20               NaN  Scott Linebrink  407489.0  276530.0          NaN  ...
21               NaN  Scott Linebrink  150484.0  276530.0    strikeout  ...
22               NaN  Scott Linebrink  150484.0  276530.0          NaN  ...
23               NaN  Scott Linebrink  150484.0  276530.0          NaN  ...
24               NaN  Scott Linebrink  150484.0  276530.0          NaN  ...
25               NaN  Scott Linebrink  452252.0  276530.0    strikeout  ...
26               NaN  Scott Linebrink  452252.0  276530.0          NaN  ...
27               NaN  Scott Linebrink  452252.0  276530.0          NaN  ...
28               NaN  Scott Linebrink  136460.0  276530.0       single  ...
29               NaN  Scott Linebrink  136460.0  276530.0          NaN  ...
...              ...              ...       ...       ...          ...  ...
39970            NaN    James Russell  466320.0  460701.0          NaN  ...
39971            NaN    James Russell  466320.0  460701.0          NaN  ...
39972            NaN    James Russell  466320.0  460701.0          NaN  ...
39973            NaN    James Russell  466320.0  460701.0          NaN  ...
39974            NaN    James Russell  466320.0  460701.0          NaN  ...
39975            NaN    James Russell  466320.0  460701.0          NaN  ...
39976            NaN    James Russell  466320.0  460701.0          NaN  ...
39977            NaN    James Russell  466320.0  460701.0          NaN  ...
39978            NaN    James Russell  117955.0  460701.0     sac_bunt  ...
39979            NaN    James Russell  434661.0  460701.0       single  ...
39980            NaN       Derek Lowe  150093.0  117955.0    strikeout  ...
39981            NaN       Derek Lowe  150093.0  117955.0          NaN  ...
39982            NaN       Derek Lowe  150093.0  117955.0          NaN  ...
39983            NaN       Derek Lowe  407781.0  117955.0  double_play  ...
39984            NaN       Derek Lowe  407781.0  117955.0          NaN  ...
39985            NaN       Derek Lowe  133380.0  117955.0       single  ...
39986            NaN       Derek Lowe  133380.0  117955.0          NaN  ...
39987            NaN       Derek Lowe  133380.0  117955.0          NaN  ...
39988            NaN       Derek Lowe  133380.0  117955.0          NaN  ...
39989            NaN    James Russell  518792.0  460701.0    strikeout  ...
39990            NaN    James Russell  518792.0  460701.0          NaN  ...
39991            NaN    James Russell  518792.0  460701.0          NaN  ...
39992            NaN    James Russell  518792.0  460701.0          NaN  ...
39993            NaN    James Russell  488862.0  460701.0    field_out  ...
39994            NaN    James Russell  488862.0  460701.0          NaN  ...
39995            NaN    James Russell  488862.0  460701.0          NaN  ...
39996            NaN    James Russell  136267.0  460701.0       single  ...
39997            NaN    James Russell  136267.0  460701.0          NaN  ...
39998            NaN    James Russell  435263.0  460701.0    field_out  ...
39999            NaN    James Russell  435263.0  460701.0          NaN  ...

      home_score  away_score bat_score fld_score post_away_score  \
0            7.0         3.0       3.0       7.0             3.0
1            7.0         3.0       3.0       7.0             3.0
2            7.0         3.0       3.0       7.0             3.0
3            7.0         3.0       3.0       7.0             3.0
4            7.0         3.0       3.0       7.0             3.0
5            7.0         3.0       3.0       7.0             3.0
6            7.0         3.0       3.0       7.0             3.0
7            7.0         3.0       3.0       7.0             3.0
8            7.0         3.0       3.0       7.0             3.0
9            7.0         3.0       3.0       7.0             3.0
10           7.0         3.0       3.0       7.0             3.0
11           7.0         3.0       3.0       7.0             3.0
12           7.0         3.0       3.0       7.0             3.0
13           7.0         3.0       7.0       3.0             3.0
14           7.0         3.0       7.0       3.0             3.0
15           7.0         3.0       7.0       3.0             3.0
16           7.0         3.0       7.0       3.0             3.0
17           7.0         3.0       7.0       3.0             3.0
18           7.0         3.0       7.0       3.0             3.0
19           7.0         3.0       7.0       3.0             3.0
20           7.0         3.0       7.0       3.0             3.0
21           7.0         3.0       7.0       3.0             3.0
22           7.0         3.0       7.0       3.0             3.0
23           7.0         3.0       7.0       3.0             3.0
24           7.0         3.0       7.0       3.0             3.0
25           7.0         3.0       7.0       3.0             3.0
26           7.0         3.0       7.0       3.0             3.0
27           7.0         3.0       7.0       3.0             3.0
28           7.0         3.0       7.0       3.0             3.0
29           7.0         3.0       7.0       3.0             3.0
...          ...         ...       ...       ...             ...
39970        8.0         5.0       8.0       5.0             5.0
39971        8.0         5.0       8.0       5.0             5.0
39972        8.0         5.0       8.0       5.0             5.0
39973        8.0         5.0       8.0       5.0             5.0
39974        8.0         5.0       8.0       5.0             5.0
39975        8.0         5.0       8.0       5.0             5.0
39976        8.0         5.0       8.0       5.0             5.0
39977        8.0         5.0       8.0       5.0             5.0
39978        8.0         5.0       8.0       5.0             5.0
39979        8.0         5.0       8.0       5.0             5.0
39980        8.0         5.0       5.0       8.0             5.0
39981        8.0         5.0       5.0       8.0             5.0
39982        8.0         5.0       5.0       8.0             5.0
39983        8.0         5.0       5.0       8.0             5.0
39984        8.0         5.0       5.0       8.0             5.0
39985        8.0         5.0       5.0       8.0             5.0
39986        8.0         5.0       5.0       8.0             5.0
39987        8.0         5.0       5.0       8.0             5.0
39988        8.0         5.0       5.0       8.0             5.0
39989        8.0         5.0       8.0       5.0             5.0
39990        8.0         5.0       8.0       5.0             5.0
39991        8.0         5.0       8.0       5.0             5.0
39992        8.0         5.0       8.0       5.0             5.0
39993        8.0         5.0       8.0       5.0             5.0
39994        8.0         5.0       8.0       5.0             5.0
39995        8.0         5.0       8.0       5.0             5.0
39996        8.0         5.0       8.0       5.0             5.0
39997        8.0         5.0       8.0       5.0             5.0
39998        8.0         5.0       8.0       5.0             5.0
39999        8.0         5.0       8.0       5.0             5.0

      post_home_score post_bat_score post_fld_score  if_fielding_alignment  \
0                 7.0            3.0            7.0                    NaN
1                 7.0            3.0            7.0                    NaN
2                 7.0            3.0            7.0                    NaN
3                 7.0            3.0            7.0                    NaN
4                 7.0            3.0            7.0                    NaN
5                 7.0            3.0            7.0                    NaN
6                 7.0            3.0            7.0                    NaN
7                 7.0            3.0            7.0                    NaN
8                 7.0            3.0            7.0                    NaN
9                 7.0            3.0            7.0                    NaN
10                7.0            3.0            7.0                    NaN
11                7.0            3.0            7.0                    NaN
12                7.0            3.0            7.0                    NaN
13                7.0            7.0            3.0                    NaN
14                7.0            7.0            3.0                    NaN
15                7.0            7.0            3.0                    NaN
16                7.0            7.0            3.0                    NaN
17                7.0            7.0            3.0                    NaN
18                7.0            7.0            3.0                    NaN
19                7.0            7.0            3.0                    NaN
20                7.0            7.0            3.0                    NaN
21                7.0            7.0            3.0                    NaN
22                7.0            7.0            3.0                    NaN
23                7.0            7.0            3.0                    NaN
24                7.0            7.0            3.0                    NaN
25                7.0            7.0            3.0                    NaN
26                7.0            7.0            3.0                    NaN
27                7.0            7.0            3.0                    NaN
28                7.0            7.0            3.0                    NaN
29                7.0            7.0            3.0                    NaN
...               ...            ...            ...                    ...
39970             8.0            8.0            5.0                    NaN
39971             8.0            8.0            5.0                    NaN
39972             8.0            8.0            5.0                    NaN
39973             8.0            8.0            5.0                    NaN
39974             8.0            8.0            5.0                    NaN
39975             8.0            8.0            5.0                    NaN
39976             8.0            8.0            5.0                    NaN
39977             8.0            8.0            5.0                    NaN
39978             8.0            8.0            5.0                    NaN
39979             8.0            8.0            5.0                    NaN
39980             8.0            5.0            8.0                    NaN
39981             8.0            5.0            8.0                    NaN
39982             8.0            5.0            8.0                    NaN
39983             8.0            5.0            8.0                    NaN
39984             8.0            5.0            8.0                    NaN
39985             8.0            5.0            8.0                    NaN
39986             8.0            5.0            8.0                    NaN
39987             8.0            5.0            8.0                    NaN
39988             8.0            5.0            8.0                    NaN
39989             8.0            8.0            5.0                    NaN
39990             8.0            8.0            5.0                    NaN
39991             8.0            8.0            5.0                    NaN
39992             8.0            8.0            5.0                    NaN
39993             8.0            8.0            5.0                    NaN
39994             8.0            8.0            5.0                    NaN
39995             8.0            8.0            5.0                    NaN
39996             8.0            8.0            5.0                    NaN
39997             8.0            8.0            5.0                    NaN
39998             8.0            8.0            5.0                    NaN
39999             8.0            8.0            5.0                    NaN

      of_fielding_alignment
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN
14                      NaN
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN
20                      NaN
21                      NaN
22                      NaN
23                      NaN
24                      NaN
25                      NaN
26                      NaN
27                      NaN
28                      NaN
29                      NaN
...                     ...
39970                   NaN
39971                   NaN
39972                   NaN
39973                   NaN
39974                   NaN
39975                   NaN
39976                   NaN
39977                   NaN
39978                   NaN
39979                   NaN
39980                   NaN
39981                   NaN
39982                   NaN
39983                   NaN
39984                   NaN
39985                   NaN
39986                   NaN
39987                   NaN
39988                   NaN
39989                   NaN
39990                   NaN
39991                   NaN
39992                   NaN
39993                   NaN
39994                   NaN
39995                   NaN
39996                   NaN
39997                   NaN
39998                   NaN
39999                   NaN

[40000 rows x 82 columns]>

In [140]:
pid = []
for x in dfp.pitcher:
    pid.append(x)
#     for x in pid :pitcher_name = pb.playerid_reverse_lookup(pid)

In [222]:
dist_pitcher = pid
count = 0
# for i in dist_pitcher:
pitchers = pb.playerid_reverse_lookup(dist_pitcher)
#     count +=1
#     print(count)

Gathering player lookup table. This may take a moment.

In [223]:
pitchers.drop(['key_retro','key_bbref','key_fangraphs','mlb_played_first','mlb_played_last'],axis=1,inplace=True)

In [225]:
pitchers['name'] = pitchers['name_first']+' '+pitchers['name_last']
pitchers.drop(['name_last','name_first'],axis=1, inplace=True)

In [226]:
dfp['pitcher']= dfp.pitcher.astype(int)
# dfp.drop(['level_0'],axis=1, inplace=True)

In [227]:
dfp.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,SL,2010-04-15,83.2,NaN,NaN,Jason Frasor,493351.0,430630,field_out,hit_into_play,...,7.0,3.0,3.0,7.0,3.0,7.0,3.0,7.0,NaN,NaN
1,SL,2010-04-15,84.3,NaN,NaN,Jason Frasor,493351.0,430630,NaN,ball,...,7.0,3.0,3.0,7.0,3.0,7.0,3.0,7.0,NaN,NaN
2,CH,2010-04-15,85.2,NaN,NaN,Jason Frasor,493351.0,430630,NaN,foul,...,7.0,3.0,3.0,7.0,3.0,7.0,3.0,7.0,NaN,NaN
3,SL,2010-04-15,85.4,NaN,NaN,Jason Frasor,493351.0,430630,NaN,foul,...,7.0,3.0,3.0,7.0,3.0,7.0,3.0,7.0,NaN,NaN
4,SL,2010-04-15,83.4,NaN,NaN,Jason Frasor,493351.0,430630,NaN,called_strike,...,7.0,3.0,3.0,7.0,3.0,7.0,3.0,7.0,NaN,NaN

In [228]:
pitchers.head()

   key_mlbam            name
0     430911   david aardsma
1     435618  jeremy accardo
2     469686  alfredo aceves
3     430606      mike adams
4     346793  jeremy affeldt

In [272]:
pitchers.set_index('key_mlbam')

                        name
key_mlbam
430911         david aardsma
435618        jeremy accardo
469686        alfredo aceves
430606            mike adams
346793        jeremy affeldt
458006           matt albers
474463        brett anderson
276520        bronson arroyo
425786        scott atchison
488674        burke badenhop
276056            danys baez
457732         andrew bailey
456701          homer bailey
435044           scott baker
346797         grant balfour
446454       brian bannister
453268           daniel bard
455374      antonio bastardo
110683        miguel batista
277417          josh beckett
279571          matt belisle
425514            heath bell
448753           justin berg
448269         brad bergesen
456589        jason bergmann
460072          jason berken
429783     rafael betancourt
451532      chad billingsley
448147        nick blackburn
460283         jerry blevins
...                      ...
450306          jason vargas
458220     esmerling vasquez
134320        javier vazquez
407842            jose veras
434378      justin verlander
453646     carlos villanueva
458690         chris volstad
123790          billy wagner
425794       adam wainwright
123801         tim wakefield
400104          tyler walker
213711           jeff weaver
450308          jered weaver
425487       todd wellemeyer
448694           randy wells
150414        jake westbrook
235095           dan wheeler
457461            sean white
430942        randy williams
425883      dontrelle willis
451216          brian wilson
450351          c. j. wilson
150116            randy wolf
445971              tim wood
124604          jamey wright
432934           chris young
407296       carlos zambrano
446899          brad ziegler
217096            barry zito
451491           joel zumaya

[375 rows x 1 columns]

In [273]:
pitchers[pitchers['key_mlbam'].iloc[[y],[pitchers.name]]]

IndexError: positional indexers are out-of-bounds

In [275]:
change_name = [] 
for x in dfp.pitcher:
    for y in pitchers.index:
        if x==y:
            change_name.append(pitchers[pitchers['key_mlbam'].iloc[[y],[pitchers.name]]])

In [166]:
dfp['pitcher_name'] = pitcher_name[dfp['pitcher']]

TypeError: tuple indices must be integers or slices, not Series

In [296]:
import pandas as pd
from pybaseball import statcast


seasons = {'2010':{'start_date': '2010-04-04', 'end_date': '2010-11-01'},
           '2011':{'start_date': '2011-03-31', 'end_date': '2011-10-28'},
           '2012':{'start_date': '2012-03-28', 'end_date': '2012-10-28'},
           '2013':{'start_date': '2013-03-31', 'end_date': '2013-10-30'},
           '2014':{'start_date': '2014-03-22', 'end_date': '2014-10-29'},
           '2015':{'start_date': '2015-04-05', 'end_date': '2015-11-01'},
           '2016':{'start_date': '2016-04-03', 'end_date': '2016-11-02'},
           '2017':{'start_date': '2017-04-02', 'end_date': '2017-11-01'},
           '2018':{'start_date': '2018-03-29', 'end_date': '2018-10-28'},
           '2019':{'start_date': '2019-03-20', 'end_date': '2019-10-30'}
           }


def pull_clean_and_pickle(start_date, end_date, year):

    # Pull in DataFrame from statcast
    df = statcast(start_dt = start_date, end_dt = end_date)

    # Drop depriciated and extraneous features
    df = df.drop(columns = ['spin_dir','spin_rate_deprecated',
         'break_angle_deprecated','break_length_deprecated', 'game_type',
         'tfs_deprecated', 'tfs_zulu_deprecated', 'umpire'])

    # Sort pitches chronologically
    df = df.sort_values(by = ['game_date', 'game_pk', 'at_bat_number', 'pitch_number'])

    # Pickle DataFrame
    df.to_pickle(path=(
    "D:/baseball_seasons/" + year + ".pkl"
    ),compression='zip')


for year in seasons.keys():
  start_date = seasons[year]['start_date']
  end_date = seasons[year]['end_date']
  pull_clean_and_pickle(start_date, end_date, year)

This is a large query, it may take a moment to complete
Completed sub-query from 2010-04-04 to 2010-04-09
Completed sub-query from 2010-04-10 to 2010-04-15
Completed sub-query from 2010-04-16 to 2010-04-21
Completed sub-query from 2010-04-22 to 2010-04-27
Completed sub-query from 2010-04-28 to 2010-05-03
Completed sub-query from 2010-05-04 to 2010-05-09
Completed sub-query from 2010-05-10 to 2010-05-15
Completed sub-query from 2010-05-16 to 2010-05-21
Completed sub-query from 2010-05-22 to 2010-05-27
Completed sub-query from 2010-05-28 to 2010-06-02
Completed sub-query from 2010-06-03 to 2010-06-08
Completed sub-query from 2010-06-09 to 2010-06-14
Completed sub-query from 2010-06-15 to 2010-06-20
Completed sub-query from 2010-06-21 to 2010-06-26
Completed sub-query from 2010-06-27 to 2010-07-02
Completed sub-query from 2010-07-03 to 2010-07-08
Completed sub-query from 2010-07-09 to 2010-07-14
Completed sub-query from 2010-07-15 to 2010-07-20
Completed sub-query from 2010-07-21 to 2010-07-26
Completed sub-query from 2010-07-27 to 2010-08-01
Completed sub-query from 2010-08-02 to 2010-08-07
Completed sub-query from 2010-08-08 to 2010-08-13
Completed sub-query from 2010-08-14 to 2010-08-19
Completed sub-query from 2010-08-20 to 2010-08-25
Completed sub-query from 2010-08-26 to 2010-08-31
Completed sub-query from 2010-09-01 to 2010-09-06
Completed sub-query from 2010-09-07 to 2010-09-12
Completed sub-query from 2010-09-13 to 2010-09-18
Completed sub-query from 2010-09-19 to 2010-09-24
Completed sub-query from 2010-09-25 to 2010-09-30
Completed sub-query from 2010-10-01 to 2010-10-06
Completed sub-query from 2010-10-07 to 2010-10-12
Completed sub-query from 2010-10-13 to 2010-10-18
Completed sub-query from 2010-10-19 to 2010-10-24
Completed sub-query from 2010-10-25 to 2010-10-30
Completed sub-query from 2010-10-31 to 2010-11-01
This is a large query, it may take a moment to complete
Completed sub-query from 2011-03-31 to 2011-04-05
Completed sub-query from 2011-04-06 to 2011-04-11
Completed sub-query from 2011-04-12 to 2011-04-17
Completed sub-query from 2011-04-18 to 2011-04-23
Completed sub-query from 2011-04-24 to 2011-04-29
Completed sub-query from 2011-04-30 to 2011-05-05
Completed sub-query from 2011-05-06 to 2011-05-11
Completed sub-query from 2011-05-12 to 2011-05-17
Completed sub-query from 2011-05-18 to 2011-05-23
Completed sub-query from 2011-05-24 to 2011-05-29
Completed sub-query from 2011-05-30 to 2011-06-04
Completed sub-query from 2011-06-05 to 2011-06-10
Completed sub-query from 2011-06-11 to 2011-06-16
Completed sub-query from 2011-06-17 to 2011-06-22
Completed sub-query from 2011-06-23 to 2011-06-28
Completed sub-query from 2011-06-29 to 2011-07-04
Completed sub-query from 2011-07-05 to 2011-07-10
Completed sub-query from 2011-07-11 to 2011-07-16
Completed sub-query from 2011-07-17 to 2011-07-22
Completed sub-query from 2011-07-23 to 2011-07-28
Completed sub-query from 2011-07-29 to 2011-08-03
Completed sub-query from 2011-08-04 to 2011-08-09
Completed sub-query from 2011-08-10 to 2011-08-15
Completed sub-query from 2011-08-16 to 2011-08-21
Completed sub-query from 2011-08-22 to 2011-08-27
Completed sub-query from 2011-08-28 to 2011-09-02
Completed sub-query from 2011-09-03 to 2011-09-08
Completed sub-query from 2011-09-09 to 2011-09-14
Completed sub-query from 2011-09-15 to 2011-09-20
Completed sub-query from 2011-09-21 to 2011-09-26
Completed sub-query from 2011-09-27 to 2011-10-02
Completed sub-query from 2011-10-03 to 2011-10-08
Completed sub-query from 2011-10-09 to 2011-10-14
Completed sub-query from 2011-10-15 to 2011-10-20
Completed sub-query from 2011-10-21 to 2011-10-26
Completed sub-query from 2011-10-27 to 2011-10-28
This is a large query, it may take a moment to complete
Completed sub-query from 2012-03-28 to 2012-04-02
Completed sub-query from 2012-04-03 to 2012-04-08
Completed sub-query from 2012-04-09 to 2012-04-14
Completed sub-query from 2012-04-15 to 2012-04-20
Completed sub-query from 2012-04-21 to 2012-04-26
Completed sub-query from 2012-04-27 to 2012-05-02
Completed sub-query from 2012-05-03 to 2012-05-08
Completed sub-query from 2012-05-09 to 2012-05-14
Completed sub-query from 2012-05-15 to 2012-05-20
Completed sub-query from 2012-05-21 to 2012-05-26
Completed sub-query from 2012-05-27 to 2012-06-01
Completed sub-query from 2012-06-02 to 2012-06-07
Completed sub-query from 2012-06-08 to 2012-06-13
Completed sub-query from 2012-06-14 to 2012-06-19
Completed sub-query from 2012-06-20 to 2012-06-25
Completed sub-query from 2012-06-26 to 2012-07-01
Completed sub-query from 2012-07-02 to 2012-07-07
Completed sub-query from 2012-07-08 to 2012-07-13
Completed sub-query from 2012-07-14 to 2012-07-19
Completed sub-query from 2012-07-20 to 2012-07-25
Completed sub-query from 2012-07-26 to 2012-07-31
Completed sub-query from 2012-08-01 to 2012-08-06
Completed sub-query from 2012-08-07 to 2012-08-12
Completed sub-query from 2012-08-13 to 2012-08-18
Completed sub-query from 2012-08-19 to 2012-08-24
Completed sub-query from 2012-08-25 to 2012-08-30
Completed sub-query from 2012-08-31 to 2012-09-05
Completed sub-query from 2012-09-06 to 2012-09-11
Completed sub-query from 2012-09-12 to 2012-09-17
Completed sub-query from 2012-09-18 to 2012-09-23
Completed sub-query from 2012-09-24 to 2012-09-29
Completed sub-query from 2012-09-30 to 2012-10-05
Completed sub-query from 2012-10-06 to 2012-10-11
Completed sub-query from 2012-10-12 to 2012-10-17
Completed sub-query from 2012-10-18 to 2012-10-23
Completed sub-query from 2012-10-24 to 2012-10-28
This is a large query, it may take a moment to complete
Completed sub-query from 2013-03-31 to 2013-04-05
Completed sub-query from 2013-04-06 to 2013-04-11
Completed sub-query from 2013-04-12 to 2013-04-17
Completed sub-query from 2013-04-18 to 2013-04-23

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: DtypeWarning: Columns (8,15,23) have mixed types. Specify dtype option on import or set low_memory=False.

Completed sub-query from 2013-04-24 to 2013-04-29
Completed sub-query from 2013-04-30 to 2013-05-05
Completed sub-query from 2013-05-06 to 2013-05-11
Completed sub-query from 2013-05-12 to 2013-05-17
Completed sub-query from 2013-05-18 to 2013-05-23
Completed sub-query from 2013-05-24 to 2013-05-29
Completed sub-query from 2013-05-30 to 2013-06-04
Completed sub-query from 2013-06-05 to 2013-06-10
Completed sub-query from 2013-06-11 to 2013-06-16
Completed sub-query from 2013-06-17 to 2013-06-22
Completed sub-query from 2013-06-23 to 2013-06-28
Completed sub-query from 2013-06-29 to 2013-07-04
Completed sub-query from 2013-07-05 to 2013-07-10
Completed sub-query from 2013-07-11 to 2013-07-16
Completed sub-query from 2013-07-17 to 2013-07-22
Completed sub-query from 2013-07-23 to 2013-07-28
Completed sub-query from 2013-07-29 to 2013-08-03
Completed sub-query from 2013-08-04 to 2013-08-09
Completed sub-query from 2013-08-10 to 2013-08-15
Completed sub-query from 2013-08-16 to 2013-08-21
Completed sub-query from 2013-08-22 to 2013-08-27
Completed sub-query from 2013-08-28 to 2013-09-02
Completed sub-query from 2013-09-03 to 2013-09-08
Completed sub-query from 2013-09-09 to 2013-09-14
Completed sub-query from 2013-09-15 to 2013-09-20
Completed sub-query from 2013-09-21 to 2013-09-26
Completed sub-query from 2013-09-27 to 2013-10-02
Completed sub-query from 2013-10-03 to 2013-10-08
Completed sub-query from 2013-10-09 to 2013-10-14
Completed sub-query from 2013-10-15 to 2013-10-20
Completed sub-query from 2013-10-21 to 2013-10-26
Completed sub-query from 2013-10-27 to 2013-10-30
This is a large query, it may take a moment to complete
Completed sub-query from 2014-03-22 to 2014-03-27
Completed sub-query from 2014-03-28 to 2014-04-02
Completed sub-query from 2014-04-03 to 2014-04-08
Completed sub-query from 2014-04-09 to 2014-04-14
Completed sub-query from 2014-04-15 to 2014-04-20
Completed sub-query from 2014-04-21 to 2014-04-26
Completed sub-query from 2014-04-27 to 2014-05-02
Completed sub-query from 2014-05-03 to 2014-05-08
Completed sub-query from 2014-05-09 to 2014-05-14
Completed sub-query from 2014-05-15 to 2014-05-20
Completed sub-query from 2014-05-21 to 2014-05-26
Completed sub-query from 2014-05-27 to 2014-06-01
Completed sub-query from 2014-06-02 to 2014-06-07
Completed sub-query from 2014-06-08 to 2014-06-13
Completed sub-query from 2014-06-14 to 2014-06-19
Completed sub-query from 2014-06-20 to 2014-06-25
Completed sub-query from 2014-06-26 to 2014-07-01
Completed sub-query from 2014-07-02 to 2014-07-07
Completed sub-query from 2014-07-08 to 2014-07-13
Completed sub-query from 2014-07-14 to 2014-07-19
Completed sub-query from 2014-07-20 to 2014-07-25
Completed sub-query from 2014-07-26 to 2014-07-31
Completed sub-query from 2014-08-01 to 2014-08-06
Completed sub-query from 2014-08-07 to 2014-08-12
Completed sub-query from 2014-08-13 to 2014-08-18
Completed sub-query from 2014-08-19 to 2014-08-24
Completed sub-query from 2014-08-25 to 2014-08-30
Completed sub-query from 2014-08-31 to 2014-09-05
Completed sub-query from 2014-09-06 to 2014-09-11
Completed sub-query from 2014-09-12 to 2014-09-17
Completed sub-query from 2014-09-18 to 2014-09-23
Completed sub-query from 2014-09-24 to 2014-09-29
Completed sub-query from 2014-09-30 to 2014-10-05
Completed sub-query from 2014-10-06 to 2014-10-11
Completed sub-query from 2014-10-12 to 2014-10-17
Completed sub-query from 2014-10-18 to 2014-10-23
Completed sub-query from 2014-10-24 to 2014-10-29
This is a large query, it may take a moment to complete
Completed sub-query from 2015-04-05 to 2015-04-10
Completed sub-query from 2015-04-11 to 2015-04-16
Completed sub-query from 2015-04-17 to 2015-04-22
Completed sub-query from 2015-04-23 to 2015-04-28
Completed sub-query from 2015-04-29 to 2015-05-04
Completed sub-query from 2015-05-05 to 2015-05-10
Completed sub-query from 2015-05-11 to 2015-05-16
Completed sub-query from 2015-05-17 to 2015-05-22
Completed sub-query from 2015-05-23 to 2015-05-28
Completed sub-query from 2015-05-29 to 2015-06-03
Completed sub-query from 2015-06-04 to 2015-06-09
Completed sub-query from 2015-06-10 to 2015-06-15
Completed sub-query from 2015-06-16 to 2015-06-21
Completed sub-query from 2015-06-22 to 2015-06-27
Completed sub-query from 2015-06-28 to 2015-07-03
Completed sub-query from 2015-07-04 to 2015-07-09
Completed sub-query from 2015-07-10 to 2015-07-15
Completed sub-query from 2015-07-16 to 2015-07-21
Completed sub-query from 2015-07-22 to 2015-07-27
Completed sub-query from 2015-07-28 to 2015-08-02
Completed sub-query from 2015-08-03 to 2015-08-08
Completed sub-query from 2015-08-09 to 2015-08-14
Completed sub-query from 2015-08-15 to 2015-08-20
Completed sub-query from 2015-08-21 to 2015-08-26
Completed sub-query from 2015-08-27 to 2015-09-01
Completed sub-query from 2015-09-02 to 2015-09-07
Completed sub-query from 2015-09-08 to 2015-09-13
Completed sub-query from 2015-09-14 to 2015-09-19
Completed sub-query from 2015-09-20 to 2015-09-25
Completed sub-query from 2015-09-26 to 2015-10-01
Completed sub-query from 2015-10-02 to 2015-10-07
Completed sub-query from 2015-10-08 to 2015-10-13
Completed sub-query from 2015-10-14 to 2015-10-19
Completed sub-query from 2015-10-20 to 2015-10-25
Completed sub-query from 2015-10-26 to 2015-10-31
Completed sub-query from 2015-11-01 to 2015-11-01
This is a large query, it may take a moment to complete
Completed sub-query from 2016-04-03 to 2016-04-08
Completed sub-query from 2016-04-09 to 2016-04-14
Completed sub-query from 2016-04-15 to 2016-04-20
Completed sub-query from 2016-04-21 to 2016-04-26
Completed sub-query from 2016-04-27 to 2016-05-02
Completed sub-query from 2016-05-03 to 2016-05-08
Completed sub-query from 2016-05-09 to 2016-05-14
Completed sub-query from 2016-05-15 to 2016-05-20
Completed sub-query from 2016-05-21 to 2016-05-26
Completed sub-query from 2016-05-27 to 2016-06-01
Completed sub-query from 2016-06-02 to 2016-06-07
Completed sub-query from 2016-06-08 to 2016-06-13
Completed sub-query from 2016-06-14 to 2016-06-19
Completed sub-query from 2016-06-20 to 2016-06-25
Completed sub-query from 2016-06-26 to 2016-07-01
Completed sub-query from 2016-07-02 to 2016-07-07
Completed sub-query from 2016-07-08 to 2016-07-13
Completed sub-query from 2016-07-14 to 2016-07-19
Completed sub-query from 2016-07-20 to 2016-07-25
Completed sub-query from 2016-07-26 to 2016-07-31
Completed sub-query from 2016-08-01 to 2016-08-06
Completed sub-query from 2016-08-07 to 2016-08-12
Completed sub-query from 2016-08-13 to 2016-08-18
Completed sub-query from 2016-08-19 to 2016-08-24
Completed sub-query from 2016-08-25 to 2016-08-30
Completed sub-query from 2016-08-31 to 2016-09-05
Completed sub-query from 2016-09-06 to 2016-09-11
Completed sub-query from 2016-09-12 to 2016-09-17
Completed sub-query from 2016-09-18 to 2016-09-23
Completed sub-query from 2016-09-24 to 2016-09-29
Completed sub-query from 2016-09-30 to 2016-10-05
Completed sub-query from 2016-10-06 to 2016-10-11
Completed sub-query from 2016-10-12 to 2016-10-17
Completed sub-query from 2016-10-18 to 2016-10-23
Completed sub-query from 2016-10-24 to 2016-10-29
Completed sub-query from 2016-10-30 to 2016-11-02
This is a large query, it may take a moment to complete
Completed sub-query from 2017-04-02 to 2017-04-07
Completed sub-query from 2017-04-08 to 2017-04-13
Completed sub-query from 2017-04-14 to 2017-04-19
Completed sub-query from 2017-04-20 to 2017-04-25
Completed sub-query from 2017-04-26 to 2017-05-01
Completed sub-query from 2017-05-02 to 2017-05-07
Completed sub-query from 2017-05-08 to 2017-05-13
Completed sub-query from 2017-05-14 to 2017-05-19
Completed sub-query from 2017-05-20 to 2017-05-25
Completed sub-query from 2017-05-26 to 2017-05-31
Completed sub-query from 2017-06-01 to 2017-06-06
Completed sub-query from 2017-06-07 to 2017-06-12
Completed sub-query from 2017-06-13 to 2017-06-18
Completed sub-query from 2017-06-19 to 2017-06-24
Completed sub-query from 2017-06-25 to 2017-06-30
Completed sub-query from 2017-07-01 to 2017-07-06
Completed sub-query from 2017-07-07 to 2017-07-12
Completed sub-query from 2017-07-13 to 2017-07-18
Completed sub-query from 2017-07-19 to 2017-07-24

Completed sub-query from 2017-07-25 to 2017-07-30
Completed sub-query from 2017-07-31 to 2017-08-05
Completed sub-query from 2017-08-06 to 2017-08-11
Completed sub-query from 2017-08-12 to 2017-08-17
Completed sub-query from 2017-08-18 to 2017-08-23
Completed sub-query from 2017-08-24 to 2017-08-29
Completed sub-query from 2017-08-30 to 2017-09-04
Completed sub-query from 2017-09-05 to 2017-09-10
Completed sub-query from 2017-09-11 to 2017-09-16
Completed sub-query from 2017-09-17 to 2017-09-22
Completed sub-query from 2017-09-23 to 2017-09-28
Completed sub-query from 2017-09-29 to 2017-10-04
Completed sub-query from 2017-10-05 to 2017-10-10
Completed sub-query from 2017-10-11 to 2017-10-16
Completed sub-query from 2017-10-17 to 2017-10-22
Completed sub-query from 2017-10-23 to 2017-10-28
Completed sub-query from 2017-10-29 to 2017-11-01
This is a large query, it may take a moment to complete
Completed sub-query from 2018-03-29 to 2018-04-03
Completed sub-query from 2018-04-04 to 2018-04-09
Completed sub-query from 2018-04-10 to 2018-04-15
Completed sub-query from 2018-04-16 to 2018-04-21
Completed sub-query from 2018-04-22 to 2018-04-27
Completed sub-query from 2018-04-28 to 2018-05-03
Completed sub-query from 2018-05-04 to 2018-05-09
Completed sub-query from 2018-05-10 to 2018-05-15
Completed sub-query from 2018-05-16 to 2018-05-21
Completed sub-query from 2018-05-22 to 2018-05-27
Completed sub-query from 2018-05-28 to 2018-06-02
Completed sub-query from 2018-06-03 to 2018-06-08
Completed sub-query from 2018-06-09 to 2018-06-14
Completed sub-query from 2018-06-15 to 2018-06-20
Completed sub-query from 2018-06-21 to 2018-06-26
Completed sub-query from 2018-06-27 to 2018-07-02
Completed sub-query from 2018-07-03 to 2018-07-08
Completed sub-query from 2018-07-09 to 2018-07-14
Completed sub-query from 2018-07-15 to 2018-07-20
Completed sub-query from 2018-07-21 to 2018-07-26
Completed sub-query from 2018-07-27 to 2018-08-01
Completed sub-query from 2018-08-02 to 2018-08-07
Completed sub-query from 2018-08-08 to 2018-08-13
Completed sub-query from 2018-08-14 to 2018-08-19
Completed sub-query from 2018-08-20 to 2018-08-25
Completed sub-query from 2018-08-26 to 2018-08-31
Completed sub-query from 2018-09-01 to 2018-09-06
Completed sub-query from 2018-09-07 to 2018-09-12
Completed sub-query from 2018-09-13 to 2018-09-18
Completed sub-query from 2018-09-19 to 2018-09-24
Completed sub-query from 2018-09-25 to 2018-09-30
Completed sub-query from 2018-10-01 to 2018-10-06
Completed sub-query from 2018-10-07 to 2018-10-12
Completed sub-query from 2018-10-13 to 2018-10-18
Completed sub-query from 2018-10-19 to 2018-10-24
Completed sub-query from 2018-10-25 to 2018-10-28
This is a large query, it may take a moment to complete
Completed sub-query from 2019-03-20 to 2019-03-25
Completed sub-query from 2019-03-26 to 2019-03-31
Completed sub-query from 2019-04-01 to 2019-04-06
Completed sub-query from 2019-04-07 to 2019-04-12
Completed sub-query from 2019-04-13 to 2019-04-18
Completed sub-query from 2019-04-19 to 2019-04-24
Completed sub-query from 2019-04-25 to 2019-04-30
Completed sub-query from 2019-05-01 to 2019-05-06
Completed sub-query from 2019-05-07 to 2019-05-12
Completed sub-query from 2019-05-13 to 2019-05-18
Completed sub-query from 2019-05-19 to 2019-05-24
Completed sub-query from 2019-05-25 to 2019-05-30
Completed sub-query from 2019-05-31 to 2019-06-05
Completed sub-query from 2019-06-06 to 2019-06-11
Completed sub-query from 2019-06-12 to 2019-06-17
Completed sub-query from 2019-06-18 to 2019-06-23
Completed sub-query from 2019-06-24 to 2019-06-29
Completed sub-query from 2019-06-30 to 2019-07-05
Completed sub-query from 2019-07-06 to 2019-07-11
Completed sub-query from 2019-07-12 to 2019-07-17
Completed sub-query from 2019-07-18 to 2019-07-23
Completed sub-query from 2019-07-24 to 2019-07-29
Completed sub-query from 2019-07-30 to 2019-08-04
Completed sub-query from 2019-08-05 to 2019-08-10
Completed sub-query from 2019-08-11 to 2019-08-16
Completed sub-query from 2019-08-17 to 2019-08-22
Completed sub-query from 2019-08-23 to 2019-08-28
Completed sub-query from 2019-08-29 to 2019-09-03
Completed sub-query from 2019-09-04 to 2019-09-09
Completed sub-query from 2019-09-10 to 2019-09-15
Completed sub-query from 2019-09-16 to 2019-09-21
Completed sub-query from 2019-09-22 to 2019-09-27
Completed sub-query from 2019-09-28 to 2019-10-03
Query unsuccessful for data from 2019-10-04 to 2019-10-08. Skipping these dates.
Query unsuccessful for data from 2019-10-09 to 2019-10-09. Skipping these dates.
Query unsuccessful for data from 2019-10-10 to 2019-10-14. Skipping these dates.
Query unsuccessful for data from 2019-10-15 to 2019-10-15. Skipping these dates.
Query unsuccessful for data from 2019-10-16 to 2019-10-20. Skipping these dates.
Query unsuccessful for data from 2019-10-21 to 2019-10-21. Skipping these dates.
Query unsuccessful for data from 2019-10-22 to 2019-10-26. Skipping these dates.
Query unsuccessful for data from 2019-10-27 to 2019-10-27. Skipping these dates.
Completed sub-query from 2019-10-28 to 2019-10-30

In [304]:
df_10 = pd.read_pickle('D:/baseball_seasons/2010.pkl',compression='zip')
df_11 = pd.read_pickle('D:/baseball_seasons/2011.pkl',compression='zip')
df_12 = pd.read_pickle('D:/baseball_seasons/2012.pkl',compression='zip')
df_13 = pd.read_pickle('D:/baseball_seasons/2013.pkl',compression='zip')
df_14 = pd.read_pickle('D:/baseball_seasons/2014.pkl',compression='zip')
df_15 = pd.read_pickle('D:/baseball_seasons/2015.pkl',compression='zip')
df_16 = pd.read_pickle('D:/baseball_seasons/2016.pkl',compression='zip')
df_17 = pd.read_pickle('D:/baseball_seasons/2017.pkl',compression='zip')
df_18 = pd.read_pickle('D:/baseball_seasons/2018.pkl',compression='zip')
df_19 = pd.read_pickle('D:/baseball_seasons/2019.pkl',compression='zip')

In [345]:
class clean:
    """
    """

    def __init__(self):
        pass


    self.drop_columns = [
        'spin_dir',
        'spin_rate_deprecated',
        'break_angle_deprecated',
        'break_length_deprecated',
        'game_type',
        'tfs_deprecated',
        'tfs_zulu_deprecated',
        'umpire'
        ]


    def drop_columns(columns = self.drop_columns):
        """
        Drop depreciated and extraneous features
        """
        df = df.drop(columns)


    def sort_pitches():
        """
        Sort pitches chronologically
        """
        df = df.sort_values(by = [
            'game_date',
            'game_pk',
            'at_bat_number',
            'pitch_number'
            ])


    def pitch_types_cleaner():
        """
        Fills pitch type nan with a random choice with the pitch type
        prior probability as weights
        """
        # Replace UN with nan
        df['pitch_type'] = df['pitch_type'].replace({'UN':np.nan})

        # Get all the unique pitcher names in the df
        pitcher_list = df.player_name.unique().tolist()

        # Initialize empty dictionary to store each pitcher and their pitches and
        # Percentages for each pitch
        pitcher_dict = {}

        # Iterate over each pitcher:
        for pitcher in pitcher_list:
            # Assign the normalized value_counts to a variable
            pitch_percentages = df[df.player_name == pitcher].pitch_type.value_counts(normalize=True)
            # Convert that Series object to a dict and assign it as the value to
            # The pitcher dictionary
            # (Pitcher name as key)
            pitcher_dict[pitcher] = pitch_percentages.to_dict()

        # Grab the rows where pitch_type is null:
        nulls = df[df.pitch_type.isna()]

        # Iterate over each null row and assign value
        for index, row in nulls.iterrows():
          population = list(pitcher_dict[row.player_name].keys())
          weights = list(pitcher_dict[row.player_name].values())
          try:
            pitch = random.choices(population, weights, k=1)[0]
          except IndexError:
            pitch = 'FF'
          df.at[index, 'pitch_type'] = pitch


    def create_pitch_category():
        """
        """
        # Create map for pitch type into categories:
        pitch_type_map = {
            'FA':'fastball', 'FF':'fastball', 'FT':'fastball', 'FC':'fastball',
            'FS':'fastball', 'SI':'fastball', 'SF':'fastball', 'SL':'breaking',
            'CB':'breaking', 'CU':'breaking', 'SC':'breaking', 'KC':'breaking',
            'CH':'offspeed', 'KN':'offspeed', 'EP':'offspeed', 'FO':'pitchout',
            'PO':'pitchout'
            }

        # Create pitch cateogory feature
        df['pitch_cat'] = df['pitch_type']
        df['pitch_cat'] = df['pitch_cat'].replace(pitch_type_map)


    def typecast_columns():
        df['if_fielding_alignment'] = df['if_fielding_alignment'].astype(object)
        df['of_fielding_alignment'] = df['of_fielding_alignment'].astype(object)


    def create_swung():
        """
        Create swung feature
        """
        def swung(x):
            swung = [
                'foul','hit_into_play','swinging_strike','hit_into_play_no_out',
                'hit_into_play_score','foul_tip','swinging_strike_blocked',
                'foul_bunt','missed_bunt'
            ]
            return 1 if x in swung else 0
        df['batter_swung'] = df['description'].apply(swung)


    def create_strikezone_swung_chase():
        """
        """
        # Initialize in_strikezone and chased features:
        df['in_strikezone'] = 1
        df['chased'] = 0

        # Iterate through each row
        for index, row in df.iterrows():
            #if ball is outside the strikezone, change the value for that row to 0
            if row.plate_z > row.sz_top or row.plate_z < row.sz_bot or row.plate_x < -0.73 or row.plate_x > 0.73:
                df.at[index, 'in_strikezone'] = 0
            #if batter_swung at ball outside the strike zone, change chased value to 1:
            if df.at[index, 'batter_swung'] == 1 and df.at[index, 'in_strikezone'] == 0:
                df.at[index, 'chased'] = 1


    def run(df):
        """
        Clean
        """
        df = df.copy()
        drop_columns()
        sort_pitches()
        pitch_types_cleaner()
        create_pitch_category()
        typecast_columns()
        create_swung()
        create_strikezone_swung_chase()
        return df

NameError: name 'self' is not defined

In [346]:
import mrclean

ModuleNotFoundError: No module named 'mrclean'

In [344]:
df10 = Clean.run(df_10)

NameError: name 'drop_columns' is not defined